version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    allow:
      - dependency-type: all
    schedule:
      interval: monthly
    groups:
      opentelemetry:
        applies-to: version-updates
        patterns:
          - go.opentelemetry.io/*
      golang-x:
        applies-to: version-updates
        patterns:
          - golang.org/x/*
      prometheus:
        applies-to: version-updates
        patterns:
          - github.com/prometheus/*
      libcap:
        applies-to: version-updates
        patterns:
          - kernel.org/pub/linux/libs/security/libcap/*
