version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - dupword
    - err113
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - godot
    - gosec
    - noinlineerr
    - prealloc
    - funcorder
    - ireturn
    - lll
    - mnd
    - nakedret
    - nilerr # https://github.com/gostaticanalysis/nilerr/issues/8
    - nlreturn
    - noctx
    - nonamedreturns
    - paralleltest
    - tagliatelle
    - testpackage
    - thelper
    - varnamelen
    - wastedassign # https://github.com/sanposhiho/wastedassign/issues/39
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    staticcheck:
      checks: ["ALL", "-QF1006"]
  exclusions:
    rules:
      - path: (.+)\.go$
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked
      - path: (.+)\.go$
        text: should have a package comment
formatters:
  enable:
    - gofmt
    - goimports
